# Generated by Django 5.2.7 on 2026-05-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_file_deleted_at_file_is_deleted_alter_file_user'),
        ('storage', '0005_sharelink_delete_fileshare'),
    ]

    operations = [
    ]
