# Generated by Django 5.2.7 on 2026-05-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_merge_20260510_2127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShareLink',
        ),
    ]
